name: "Tools - Validate Dockerfile Schema"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  validate-json-schema:
    name: Validate JSON Schema
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
