name: "Tools - Validate YAML Schema"

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.yamllint'
      - '**.yaml'
      - '**.yml'
      - '**.yml.example'

jobs:
  validate-yaml:
    name: YAML Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint .

#      - name: Frencks yamllint
#        uses: frenck/action-yamllint@v1.5.0
