name: "Tools - Validate YAML Schema"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-yaml:
    name: YAML Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint .
